### ISSUE TITLE
Не отображает одну статью на Мапале

### ISSUE THREAD

**Issue by litrbooh** [dacom-dark-sun/mapala#101]
Постил через мапалу 2 статьи в Стимит, но отображается почему-то только одна:
![default](https://cloud.githubusercontent.com/assets/22373216/23038933/d3808d72-f49c-11e6-9fe5-c36c68f9bed9.png)

![default](https://cloud.githubusercontent.com/assets/22373216/23038946/dd07beb0-f49c-11e6-8219-6933b8490a64.png)

**Comment by dacom-dark-sun** [comment]
У нас нода как раз в тот период отключалась, после следующего репарсинга (на днях запустим) - все встанет на свои места

**Comment by litrbooh** [comment]
Т.е. статья появится, или она уже потеряна для мапалы? :)

**Comment by lehard** [comment]
Появиться
