### ISSUE TITLE
Ошибка при авторизации через Github и FB

### ISSUE THREAD

**Issue by lehard** [dacom-dark-sun/mapala#11]
![image](https://cloud.githubusercontent.com/assets/22220976/21292443/dcbe2902-c527-11e6-8ce3-d7213d6b50e6.png)

![image](https://cloud.githubusercontent.com/assets/22220976/21292448/f55a1c28-c527-11e6-95d7-320b1731c12f.png)

**Comment by dacom-dark-sun** [comment]
Регистрацию через социальные сети временно (а может и не временно) закрыли
