### ISSUE TITLE
Пропала кнопка "ВК"

### ISSUE THREAD

**Issue by asia888** [dacom-dark-sun/mapala#117]
https://mapala.net/boddhisattva/golubaya-zhemchuzhina-kyrgyzstana--ozero-issyk-kulx-chastx-5---dikiij-plyazh

**Comment by lehard** [comment]
да я тоже наблюдал этот баг несколько раз. Ещё вместе с этой кнопкой одновременно бывает пропадает кнопка редактирования поста

**Comment by asia888** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Синхронизация проблем пользователей и Github](https://trello.com/c/odqMCULk/5-github)

**Comment by asia888** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ведение таблицы статистики](https://trello.com/c/nzDyHIdP/4--)
