### ISSUE TITLE
Отображает неверное количество апвотов

### ISSUE THREAD

**Issue by lehard** [dacom-dark-sun/mapala#13]
на примере arcange

![image](https://cloud.githubusercontent.com/assets/22220976/21292750/c37358ba-c530-11e6-9bb1-5632e62c9987.png)

![image](https://cloud.githubusercontent.com/assets/22220976/21292752/ca5774ea-c530-11e6-86fe-15bfb1bd6bba.png)

**Comment by dacom-dark-sun** [comment]
Надо помониторить еще, в режиме теста парсер иногда отключается..
