### ISSUE TITLE
Нет тэгов

### ISSUE THREAD

**Issue by lehard** [dacom-dark-sun/mapala#18]
![screenshot](https://cloud.githubusercontent.com/assets/22220976/21403464/acf648f8-c7de-11e6-9073-6934a0cd4c9a.png)

внутри

![image](https://cloud.githubusercontent.com/assets/22220976/21403476/b86d814c-c7de-11e6-9682-dcaec71cfaeb.png)

ссылка на пост http://mapala.net/?author=magnebit&permlink=vy-mozhete-postroit-ego

**Comment by dacom-dark-sun** [comment]
решено
