### ISSUE TITLE
Ошибка соединения

### ISSUE THREAD

**Issue by lehard** [dacom-dark-sun/mapala#58]
а) При длительном ожидании без отправки статьи (при ее редактировании) появляется ошибка на строчке 145 steem.min.js 
        I("Closed WS connection with", i), t.isOpen = !1, delete t.ws, t.stop(), e.isPending() && n(new Error("The WS connection was closed before this operation was made")) 
                             
Вместо отображения этой ошибки необходимо пересоздавать соединение. Оригинал steem.min.js лучше не трогать, а ввести изменения в наши js файлы, которые бы пересоздавали соединение и нейтрализовывали ошибку.  
Функции Comment, Vote, DownVote, Reply: https://github.com/dacom-dark-sun/mapala/blob/master/frontend/web/js/tr.js

При вызове check_pub_key_steem
или
check_pub_key_golos

нужно проверять объект err на отсутствие ошибок, и если она есть (The WS connection was closed before this operation was made») - пересоздавать соединение.

**Comment by dacom-dark-sun** [comment]
Развернуть WebSocket сервер на ws.mapala.net
