### ISSUE TITLE
Поправить перевод английской версии

### ISSUE THREAD

**Issue by lehard** [dacom-dark-sun/mapala#66]
ливчат на русском

![image](https://cloud.githubusercontent.com/assets/22220976/22780825/e488887e-eee1-11e6-84d2-4760645ffab1.png)

**Comment by lehard** [comment]
Надпись Важно!

![image](https://cloud.githubusercontent.com/assets/22220976/22780872/0f58c578-eee2-11e6-98a2-a340381ba445.png)

**Comment by lehard** [comment]
Убрать в английской версии вкладку ICO

**Comment by lehard** [comment]
Файл не выбран

![image](https://cloud.githubusercontent.com/assets/22220976/22780933/48d77574-eee2-11e6-9eaf-606d23168fae.png)

**Comment by lehard** [comment]
Кнопка назад

![image](https://cloud.githubusercontent.com/assets/22220976/22780975/6f6a1638-eee2-11e6-97c4-b1bd302b94e3.png)

**Comment by lehard** [comment]
Язык гугл карт у нас в настройках задётся или определяется по IP или языку браузера?

![image](https://cloud.githubusercontent.com/assets/22220976/22781031/aa367b12-eee2-11e6-9ae4-f20066a882b4.png)

**Comment by lehard** [comment]
Блог автора

![image](https://cloud.githubusercontent.com/assets/22220976/22781120/fb52576e-eee2-11e6-8eaa-e7e151469213.png)

**Comment by lehard** [comment]
Когда находишься в посте

![image](https://cloud.githubusercontent.com/assets/22220976/22781162/18e25522-eee3-11e6-983c-351c207dad0f.png)

**Comment by dacom-dark-sun** [comment]
fixed
