### ISSUE TITLE
Различается количество голосов

### ISSUE THREAD

**Issue by lehard** [dacom-dark-sun/mapala#98]
102 и 196 на момент написания этого issue

https://golos.io/mapala/@mapala/blog-mapala-pervaya-razrabotka-feijl-vstrecha-s-lehard
http://mapala.net/mapala/blog-mapala-pervaya-razrabotka-feijl-vstrecha-s-lehard

Ну и сумма))

**Comment by dacom-dark-sun** [comment]
Требуется репарсинг
